package roulette;

//Import packages
import javax.swing.*;

import org.omg.CORBA.VersionSpecHelper;

import java.awt.*;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

//Main class
public class UI {
	// Declare variables
	static JFrame frame;
	static Container pane;
	static JButton btnConnect, btnDisconnect;
	static JLabel lblServer, lblUsername, lblPassword, lblPort;
	static JTextField txtServer, txtUsername, txtPassword, txtPort;
	static Insets insets;

	public static void main(String args[]) {
		// Create the frame
		frame = new JFrame("Roulette");
		// Set its size to 800x200 pixels
		frame.setSize(1200, 400);
		frame.setLayout(new BorderLayout());
		Border whiteBorder = new LineBorder(Color.WHITE, 2);
		// Prepare panel
		// pane = frame.getContentPane();
		// insets = pane.getInsets();
		// // Apply the null layout
		// pane.setLayout(null);
		// frame.setVisible (true);
		Panel head = new Panel();
		Panel left = new Panel();
		Panel center = new Panel();
		Panel right = new Panel();
		Panel bottom = new Panel();

		frame.add(head, BorderLayout.NORTH);
		frame.add(left, BorderLayout.WEST);
		frame.add(center, BorderLayout.CENTER);
		frame.add(right, BorderLayout.EAST);
		frame.add(bottom, BorderLayout.SOUTH);

		center.setLayout(new BorderLayout());
		Panel center_left = new Panel();
		Panel center_right = new Panel();
		Panel center_center = new Panel();
		Panel center_bottom = new Panel();
		Panel center_bottom2 = new Panel();

		center.add(center_left, BorderLayout.WEST);
		center.add(center_center, BorderLayout.CENTER);
		center.add(center_right, BorderLayout.EAST);
		center.add(center_bottom, BorderLayout.SOUTH);

		JButton b0 = new JButton("0");
		JButton b1st = new JButton("1st");
		JButton b2nd = new JButton("2nd");
		JButton b3rd = new JButton("3rd");
		JButton b1 = new JButton("1");
		b1.setForeground(Color.white);
		b1.setBackground(Color.red);
		b1.setOpaque(true);
		b1.setBorderPainted(true);
		b1.setBorder(whiteBorder);
		JButton b2 = new JButton("2");
		b2.setForeground(Color.white);
		b2.setBackground(Color.black);
		b2.setOpaque(true);
		b2.setBorderPainted(true);
		b2.setBorder(whiteBorder);
		JButton b3 = new JButton("3");
		b3.setForeground(Color.white);
		b3.setBackground(Color.red);
		b3.setOpaque(true);
		b3.setBorderPainted(true);
		b3.setBorder(whiteBorder);
		JButton b4 = new JButton("4");
		b4.setForeground(Color.white);
		b4.setBackground(Color.black);
		b4.setOpaque(true);
		b4.setBorderPainted(true);
		b4.setBorder(whiteBorder);
		JButton b5 = new JButton("5");
		b5.setForeground(Color.white);
		b5.setBackground(Color.red);
		b5.setOpaque(true);
		b5.setBorderPainted(true);
		b5.setBorder(whiteBorder);
		JButton b6 = new JButton("6");
		b6.setForeground(Color.white);
		b6.setBackground(Color.black);
		b6.setOpaque(true);
		b6.setBorderPainted(true);
		b6.setBorder(whiteBorder);
		JButton b7 = new JButton("7");
		b7.setForeground(Color.white);
		b7.setBackground(Color.red);
		b7.setOpaque(true);
		b7.setBorderPainted(true);
		b7.setBorder(whiteBorder);
		JButton b8 = new JButton("8");
		b8.setForeground(Color.white);
		b8.setBackground(Color.black);
		b8.setOpaque(true);
		b8.setBorderPainted(true);
		b8.setBorder(whiteBorder);
		JButton b9 = new JButton("9");
		b9.setForeground(Color.white);
		b9.setBackground(Color.red);
		b9.setOpaque(true);
		b9.setBorderPainted(true);
		b9.setBorder(whiteBorder);
		JButton b10 = new JButton("10");
		b10.setForeground(Color.white);
		b10.setBackground(Color.black);
		b10.setOpaque(true);
		b10.setBorderPainted(true);
		b10.setBorder(whiteBorder);
		JButton b11 = new JButton("11");
		b11.setForeground(Color.white);
		b11.setBackground(Color.black);
		b11.setOpaque(true);
		b11.setBorderPainted(true);
		b11.setBorder(whiteBorder);
		JButton b12 = new JButton("12");
		b12.setForeground(Color.white);
		b12.setBackground(Color.red);
		b12.setOpaque(true);
		b12.setBorderPainted(true);
		b12.setBorder(whiteBorder);
		JButton b13 = new JButton("13");
		b13.setForeground(Color.white);
		b13.setBackground(Color.black);
		b13.setOpaque(true);
		b13.setBorderPainted(true);
		b13.setBorder(whiteBorder);
		JButton b14 = new JButton("14");
		b14.setForeground(Color.white);
		b14.setBackground(Color.red);
		b14.setOpaque(true);
		b14.setBorderPainted(true);
		b14.setBorder(whiteBorder);
		JButton b15 = new JButton("15");
		b15.setForeground(Color.white);
		b15.setBackground(Color.black);
		b15.setOpaque(true);
		b15.setBorderPainted(true);
		b15.setBorder(whiteBorder);
		JButton b16 = new JButton("16");
		b16.setForeground(Color.white);
		b16.setBackground(Color.red);
		b16.setOpaque(true);
		b16.setBorderPainted(true);
		b16.setBorder(whiteBorder);
		JButton b17 = new JButton("17");
		b17.setForeground(Color.white);
		b17.setBackground(Color.black);
		b17.setOpaque(true);
		b17.setBorderPainted(true);
		b17.setBorder(whiteBorder);
		JButton b18 = new JButton("18");
		b18.setForeground(Color.white);
		b18.setBackground(Color.red);
		b18.setOpaque(true);
		b18.setBorderPainted(true);
		b18.setBorder(whiteBorder);
		JButton b19 = new JButton("19");
		b19.setForeground(Color.white);
		b19.setBackground(Color.red);
		b19.setOpaque(true);
		b19.setBorderPainted(true);
		b19.setBorder(whiteBorder);
		JButton b20 = new JButton("20");
		b20.setForeground(Color.white);
		b20.setBackground(Color.black);
		b20.setOpaque(true);
		b20.setBorderPainted(true);
		b20.setBorder(whiteBorder);
		JButton b21 = new JButton("21");
		b21.setForeground(Color.white);
		b21.setBackground(Color.red);
		b21.setOpaque(true);
		b21.setBorderPainted(true);
		b21.setBorder(whiteBorder);
		JButton b22 = new JButton("22");
		b22.setForeground(Color.white);
		b22.setBackground(Color.black);
		b22.setOpaque(true);
		b22.setBorderPainted(true);
		b22.setBorder(whiteBorder);
		JButton b23 = new JButton("23");
		b23.setForeground(Color.white);
		b23.setBackground(Color.red);
		b23.setOpaque(true);
		b23.setBorderPainted(true);
		b23.setBorder(whiteBorder);
		JButton b24 = new JButton("24");
		b24.setForeground(Color.white);
		b24.setBackground(Color.black);
		b24.setOpaque(true);
		b24.setBorderPainted(true);
		b24.setBorder(whiteBorder);
		JButton b25 = new JButton("25");
		b25.setForeground(Color.white);
		b25.setBackground(Color.red);
		b25.setOpaque(true);
		b25.setBorderPainted(true);
		b25.setBorder(whiteBorder);
		JButton b26 = new JButton("26");
		b26.setForeground(Color.white);
		b26.setBackground(Color.black);
		b26.setOpaque(true);
		b26.setBorderPainted(true);
		b26.setBorder(whiteBorder);
		JButton b27 = new JButton("27");
		b27.setForeground(Color.white);
		b27.setBackground(Color.red);
		b27.setOpaque(true);
		b27.setBorderPainted(true);
		b27.setBorder(whiteBorder);
		JButton b28 = new JButton("28");
		b28.setForeground(Color.white);
		b28.setBackground(Color.black);
		b28.setOpaque(true);
		b28.setBorderPainted(true);
		b28.setBorder(whiteBorder);
		JButton b29 = new JButton("29");
		b29.setForeground(Color.white);
		b29.setBackground(Color.black);
		b29.setOpaque(true);
		b29.setBorderPainted(true);
		b29.setBorder(whiteBorder);
		JButton b30 = new JButton("30");
		b30.setForeground(Color.white);
		b30.setBackground(Color.red);
		b30.setOpaque(true);
		b30.setBorderPainted(true);
		b30.setBorder(whiteBorder);
		JButton b31 = new JButton("31");
		b31.setForeground(Color.white);
		b31.setBackground(Color.black);
		b31.setOpaque(true);
		b31.setBorderPainted(true);
		b31.setBorder(whiteBorder);
		JButton b32 = new JButton("32");
		b32.setForeground(Color.white);
		b32.setBackground(Color.red);
		b32.setOpaque(true);
		b32.setBorderPainted(true);
		b32.setBorder(whiteBorder);
		JButton b33 = new JButton("33");
		b33.setForeground(Color.white);
		b33.setBackground(Color.black);
		b33.setOpaque(true);
		b33.setBorderPainted(true);
		b33.setBorder(whiteBorder);
		JButton b34 = new JButton("34");
		b34.setForeground(Color.white);
		b34.setBackground(Color.red);
		b34.setOpaque(true);
		b34.setBorderPainted(true);
		b34.setBorder(whiteBorder);
		JButton b35 = new JButton("35");
		b35.setForeground(Color.white);
		b35.setBackground(Color.black);
		b35.setOpaque(true);
		b35.setBorderPainted(true);
		b35.setBorder(whiteBorder);
		JButton b36 = new JButton("36");
		b36.setForeground(Color.white);
		b36.setBackground(Color.red);
		b36.setOpaque(true);
		b36.setBorderPainted(true);
		b36.setBorder(whiteBorder);
		JButton b1_12 = new JButton("1-12");
		JButton b13_24 = new JButton("13-24");
		JButton b25_36 = new JButton("25-36");
		JButton b1_18 = new JButton("1-18");
		JButton bEVEN = new JButton("EVEN");
		JButton bRED = new JButton("RED");
		bRED.setForeground(Color.white);
		bRED.setBackground(Color.red);
		bRED.setOpaque(true);
		bRED.setBorderPainted(true);
		bRED.setBorder(whiteBorder);
		JButton bBLACK = new JButton("BLACK");
		bBLACK.setForeground(Color.white);
		bBLACK.setBackground(Color.black);
		bBLACK.setOpaque(true);
		bBLACK.setBorderPainted(true);
		bBLACK.setBorder(whiteBorder);
		JButton bODD = new JButton("ODD");
		JButton b19_36 = new JButton("19-36");

		center_left.setLayout(new GridLayout(1, 1));
		center_left.add(b0);

		center_right.setLayout(new GridLayout(3, 1));
		center_right.add(b3rd);
		center_right.add(b2nd);
		center_right.add(b1st);

		center_center.setLayout(new GridLayout(3, 12));
		center_center.add(b3);
		center_center.add(b6);
		center_center.add(b9);
		center_center.add(b12);
		center_center.add(b15);
		center_center.add(b18);
		center_center.add(b21);
		center_center.add(b24);
		center_center.add(b27);
		center_center.add(b30);
		center_center.add(b33);
		center_center.add(b36);
		center_center.add(b2);
		center_center.add(b5);
		center_center.add(b8);
		center_center.add(b11);
		center_center.add(b14);
		center_center.add(b17);
		center_center.add(b20);
		center_center.add(b23);
		center_center.add(b26);
		center_center.add(b29);
		center_center.add(b32);
		center_center.add(b35);
		center_center.add(b1);
		center_center.add(b4);
		center_center.add(b7);
		center_center.add(b10);
		center_center.add(b13);
		center_center.add(b16);
		center_center.add(b19);
		center_center.add(b22);
		center_center.add(b25);
		center_center.add(b28);
		center_center.add(b31);
		center_center.add(b34);

		center_bottom.setLayout(new GridLayout(2, 3));
		center_bottom.add(b1_12);
		center_bottom.add(b13_24);
		center_bottom.add(b25_36);

		Panel center_bottom_part1 = new Panel();
		center_bottom_part1.setLayout(new GridLayout(1, 2));
		center_bottom.add(center_bottom_part1);
		center_bottom_part1.add(b1_18);
		center_bottom_part1.add(bEVEN);

		Panel center_bottom_part2 = new Panel();
		center_bottom_part2.setLayout(new GridLayout(1, 2));
		center_bottom.add(center_bottom_part2);
		center_bottom_part2.add(bRED);
		center_bottom_part2.add(bBLACK);

		Panel center_bottom_part3 = new Panel();
		center_bottom_part3.setLayout(new GridLayout(1, 2));
		center_bottom.add(center_bottom_part3);
		center_bottom_part3.add(bODD);
		center_bottom_part3.add(b19_36);

		frame.setVisible(true);

	}
}
